# Generated by Django 3.1.7 on 2021-03-22 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('courier_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CourierType',
            fields=[
                ('courier_type', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('earnings_coef', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_start', models.TimeField()),
                ('work_end', models.TimeField()),
                ('courier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='cdrestapp.courier')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('region', models.IntegerField()),
                ('assign_time', models.DateTimeField(null=True)),
                ('complete_time', models.DateTimeField(null=True)),
                ('courier_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cdrestapp.courier')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_start', models.TimeField()),
                ('delivery_end', models.TimeField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_hours', to='cdrestapp.order')),
            ],
        ),
        migrations.CreateModel(
            name='CourierRegions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.IntegerField()),
                ('courier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='cdrestapp.courier')),
            ],
        ),
        migrations.AddField(
            model_name='courier',
            name='courier_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdrestapp.couriertype'),
        ),
    ]
