# Generated by Django 3.1.7 on 2021-03-24 14:27

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdrestapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierregions',
            name='region',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('50'))]),
        ),
    ]
