# Generated by Django 3.1.7 on 2021-03-24 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdrestapp', '0002_auto_20210324_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='region',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
